services:
  ocr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pdfs:/app/pdfs         
      - ./resultado:/app/resultado
    tty: true
    command: python /app/start_llm.py